import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import ScrollProvider from "@/lib/scroll-provider";
import PageTransition from "@/components/page-transition";
import { AnimatePresence } from "framer-motion";
import Footer from "@/components/ui/footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ScrollProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<AnimatePresence mode="wait">
							<PageTransition>
								<Header />
								{children}
								<Footer />
							</PageTransition>
						</AnimatePresence>
					</ThemeProvider>
				</body>
			</ScrollProvider>
		</html>
	);
}
